const $ = (s, root=document) => root.querySelector(s);
const $$ = (s, root=document) => [...root.querySelectorAll(s)];
$('#year').textContent = new Date().getFullYear();

const projects = {
  reel:{kicker:'REEL / SELECTED WORK',title:'VIDEO + SOUND REEL',description:'A compact overview of my approach to editing, sound design, pacing, social content and post-production.',media:'video',src:'voces-invisibles.mp4',details:[['ROLE','VIDEO EDITOR / SOUND DESIGNER'],['FOCUS','EDIT · MIX · GRADE'],['PLATFORMS','YOUTUBE · SOCIAL']]},
  levelup:{kicker:'VIDEO / LEVEL UP MORTGAGES',title:'LONG-FORM → SHORT-FORM',description:'Educational YouTube and social content edited for clarity, pacing and retention. The workflow moves from long-form story structure to vertical social cutdowns.',media:'image',src:'level-up-thumb.png',details:[['ROLE','VIDEO EDITOR'],['FOCUS','EDIT · SOUND · COLOR'],['OUTPUT','YOUTUBE · SHORTS · REELS']]},
  voces:{kicker:'AUDIO / VOCES INVISIBLES',title:'STORYTELLING THROUGH SOUND',description:'Podcast production focused on dialogue clarity, restoration, pacing and an immersive listening experience.',media:'video',src:'voces-invisibles.mp4',details:[['ROLE','AUDIO EDITOR / SOUND DESIGN'],['TOOLS','PRO TOOLS · IZOTOPE RX'],['OUTPUT','PODCAST · SOCIAL CLIPS']]},
  sound:{kicker:'AUDIO / SOUND DESIGN',title:'CLEANER SOUND. STRONGER STORY.',description:'A dedicated case-study slot for dialogue cleanup, noise reduction, restoration, mixing, sound effects and final loudness control.',media:'abstract',details:[['ROLE','AUDIO ENGINEER'],['TOOLS','PRO TOOLS · RX'],['FOCUS','RESTORATION · MIXING']]},
  social:{kicker:'SOCIAL / CONTENT',title:'ONE STORY. MULTIPLE FORMATS.',description:'A social-first workflow for turning long-form footage into short, platform-specific pieces with stronger hooks, pacing, captions and sound.',media:'abstract',details:[['ROLE','VIDEO EDITOR'],['FORMATS','9:16 · 1:1 · 16:9'],['OUTPUT','REELS · SHORTS · TIKTOK']]}
};

const modal=$('#project-modal'), modalMedia=$('#modal-media'), modalTitle=$('#modal-title'), modalKicker=$('#modal-kicker'), modalDescription=$('#modal-description'), modalDetails=$('#modal-details');
function openProject(id){const p=projects[id];if(!p)return;modalKicker.textContent=p.kicker;modalTitle.textContent=p.title;modalDescription.textContent=p.description;modalDetails.innerHTML=p.details.map(d=>`<div><strong>${d[0]}</strong>${d[1]}</div>`).join('');modalMedia.innerHTML='';if(p.media==='video'){const v=document.createElement('video');v.src=p.src;v.controls=true;v.playsInline=true;v.preload='metadata';modalMedia.appendChild(v)}else if(p.media==='image'){const i=document.createElement('img');i.src=p.src;i.alt=p.title;modalMedia.appendChild(i)}else{modalMedia.innerHTML='<div class="modal-abstract"><div class="wave-visual"><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i></div></div>'}modal.classList.add('open');modal.setAttribute('aria-hidden','false');document.body.style.overflow='hidden'}
function closeProject(){modal.classList.remove('open');modal.setAttribute('aria-hidden','true');modalMedia.innerHTML='';document.body.style.overflow=''}
$$('[data-open-project]').forEach(b=>b.addEventListener('click',()=>openProject(b.dataset.openProject)));$('.modal-close').addEventListener('click',closeProject);modal.addEventListener('click',e=>{if(e.target===modal)closeProject()});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeProject()});

const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.12});$$('.reveal').forEach(el=>observer.observe(el));

$$('.project-card video').forEach(v=>{const card=v.closest('.project-card');card.addEventListener('mouseenter',()=>v.play().catch(()=>{}));card.addEventListener('mouseleave',()=>{v.pause();v.currentTime=0})});

const menuBtn=$('.menu-btn'), mobileMenu=$('.mobile-menu');menuBtn.addEventListener('click',()=>{const open=mobileMenu.classList.toggle('open');menuBtn.setAttribute('aria-expanded',open);mobileMenu.setAttribute('aria-hidden',!open)});$$('.mobile-menu a').forEach(a=>a.addEventListener('click',()=>{mobileMenu.classList.remove('open');menuBtn.setAttribute('aria-expanded','false')}));

let audioPlaying=false;const audioBtn=$('[data-audio-toggle]');audioBtn.addEventListener('click',()=>{audioPlaying=!audioPlaying;audioBtn.innerHTML=audioPlaying?'■ STOP DEMO':'▶ PLAY DEMO';$('.audio-progress i').style.transition=audioPlaying?'width 4s linear':'none';$('.audio-progress i').style.width=audioPlaying?'100%':'0%';if(audioPlaying)setTimeout(()=>{audioPlaying=false;audioBtn.innerHTML='▶ PLAY DEMO';$('.audio-progress i').style.transition='none';$('.audio-progress i').style.width='0%'},4100)});

const dot=$('.cursor-dot'),ring=$('.cursor-ring');window.addEventListener('pointermove',e=>{dot.style.left=e.clientX+'px';dot.style.top=e.clientY+'px';ring.style.left=e.clientX+'px';ring.style.top=e.clientY+'px'});$$('a,button').forEach(el=>{el.addEventListener('mouseenter',()=>ring.style.transform='translate(-50%,-50%) scale(1.5)');el.addEventListener('mouseleave',()=>ring.style.transform='translate(-50%,-50%) scale(1)')});
